excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://getaboost.github.io
title: Get a Boost news
email: thisisgetaboost@gmail.com
author: getaboost
description: My awesome new site
paginate: 3
google_analytics: 