excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://getaboost.github.io
title: Learning curves
email: thisisgetaboost@gmail.com
author: getaboost
description: Figuring it all out
paginate: 3
google_analytics: 
